Ethereum Client Library & HCL config file [sc-1745]
chronicleprotocol/oracle-suite pull request #132
Opened 2023-03-21 13:59 UTC by MDobak

2023-03-28 13:59 UTC, teghnet commented on config.hcl
I am more convinced now that we can drop the `CFG_` prefix

2023-03-28 14:34 UTC, teghnet commented
Definitely SQUASH

2023-03-28 14:36 UTC, MDobak commented
@teghnet We always do squash merges

2023-03-29 10:53 UTC, teghnet commented on config.hcl
> +  "0xd72BA9402E9f3Ff01959D6c841DDD13615FFff42"
true, fixed

2023-03-31 11:04 UTC, teghnet requested changes
Maybe a good idea would be to move the extended comments from README to the config.hcl - closer to where it is actually useful.

also: https://github.com/chronicleprotocol/oracle-suite/pull/132/files#r1150663460

2023-03-31 12:04 UTC, teghnet approved these changes
Logically and structurally I am ok with it.

2023-03-31 12:19 UTC, konstantinzolotarev approved these changes

2023-03-31 14:57 UTC, merged