Implement new jq origins [sc-2627]
chronicleprotocol/oracle-suite pull request #159
Opened 2023-06-21 13:45 UTC by deep-quality-dev

### description of pull request:

Implemented new origins and their data models:
- binance
- bitfinex
- bitstamp
- coinbase
- gemini
- huobi
- upbit
- kraken
- okx

2023-06-21 21:03 UTC, MDobak commented on config_next.hcl
> +    url  = "https://api-pub.bitfinex.com/v2/tickers?symbols=t$${ucbase}$${ucquote}"
Small suggestion, if an API offers an endpoint that returns all symbols, it's more efficient to use it rather than making separate requests for each asset. For example, with Bitfinex, you can use `https://api-pub.bitfinex.com/v2/tickers?symbols=ALL` :)

2023-06-22 00:31 UTC, deep-quality-dev commented on config_next.hcl
> +    url  = "https://api-pub.bitfinex.com/v2/tickers?symbols=t$${ucbase}$${ucquote}"
Thank you for your review.
That makes sense to me, pairs are grouped according to the request url and pairing.
https://github.com/chronicleprotocol/oracle-suite/blob/master/pkg/datapoint/origin/tick_generic_http.go#L90
Updated.

2023-07-05 12:42 UTC, teghnet requested changes
The data models need to work before we merge them.

2023-07-05 13:16 UTC, deep-quality-dev commented
> The data models need to work before we merge them.

Could you elaborate more what need to be updated or any relevant task?

2023-07-05 14:12 UTC, teghnet approved these changes

2023-07-05 15:58 UTC, teghnet approved these changes

2023-07-05 15:59 UTC, merged