Config Updates
chronicleprotocol/oracle-suite pull request #175
Opened 2023-07-11 15:07 UTC by teghnet

2023-07-12 21:30 UTC, WesleyCharlesBlake approved these changes
so clean 👌🏻

2023-07-13 00:17 UTC, deep-quality-dev commented on cmd/gofer/main.go
> +		NewModelsCmd(&opts2),
In `NewModelsCmd` and `NewDataCmd`, they are unable to load config files, since `opts` and `opts2` are two different instance and `config.hcl` is only given in `opts` in `NewRootCommand`.

2023-07-13 00:19 UTC, deep-quality-dev requested changes
Overall, looks great, very optimized in config usage.
I found `gofernext` is unable to load config file, I created my [changes](https://github.com/chronicleprotocol/oracle-suite/commit/5fd200d91cc12c8546e06e3ee3ba6191d518d2c1) myself, hope to be helpful.

2023-07-13 09:45 UTC, teghnet commented on cmd/gofer/main.go
> +		NewModelsCmd(&opts2),
fixed

2023-07-13 09:57 UTC, merged