Add new data models
chronicleprotocol/oracle-suite pull request #186
Opened 2023-08-03 13:05 UTC by deep-quality-dev

### description of pull request:

Implemented the following data models:
- BNB/USD
- USDC/USD
- SOL/USD
- WBTC/USD
- AVAX/USD
- DAI/USD
- UNI/USD
- LINK/USD
- LDO/USD
- ARB/USD
- AAVE/USD
- OP/USD
- CRV/USD
- SNX/USD

2023-08-03 17:41 UTC, NiklasKunkel reviewed
GNO Data Model

Brainstorming list of sources:
Uniswap V3 GNO/WETH - https://info.uniswap.org/#/pools/0xf56d08221b5942c428acc5de8f78489a97fc5599
15M TVL - $100k volume - on-chain source is difficult to manipulate, we like it.

Balancer V3 GNO/WETH
https://app.balancer.fi/#/ethereum/pool/0xf4c0dd9b82da36c07605df83c8a416f11724d88b000200000000000000000026
$12,532,966 TVL that's huge and extremely difficult to manipulate, also we know their data is legit because it's coming from onchain.

Binance GNO/USDT
$6,866 | $19,906 | $83,434
not amazing market depth, but okay volume and we know Binance is heavily arbitrated by almost everyone.

Coinbase GNO/USD
$14,925 | $13,882 | $25,080
Not great market depth, but we like Coinbase as a source, we like that the quote is in USD. We know Coinbase is pretty heavily arbitraged by all the big players so shouldnt have too big of a market price dislocation here for very long before it's arbed back.

Kraken GNO/USD
$1,321 | $7,797 | $8,473
terrible market depth, terrible volume. We like that Kraken is trusted, and that it's a USD quote pair. Maybe we add this, maybe we don't.


Data Source Selection
What do we do here? We definitely want Uniswap V3 and Balancer V2. Binance and Coinbase.
The question do we add Kraken or not? So let's explore two different permutations of Data Models, one with Kraken, and one without, and see which one is safer.

**Data Model 1**
Uniswap V3 - HUGE market depth GNO/WETH
Balancer V2 - HUGE market depth  GNO/WETH
Binance GNO/USDT - $6,866 | $19,906 | $83,434
Coinbase GNO/USD - $14,925 | $13,882 | $25,080

Let's try to attack this. We have 4 sources. So attacker needs to manipulate AT LEAST 2. Uniswap V3 and Balancer V2 have such enormous market depth (15M and 12.5M respectively) that no one will try to manipulate these because it's just not economically feasible. So the only credible scenario is someone is going to attack via manipulating Binance and Coinbase. Attack via this method is definitely possible because market depth liquidity is limited. However even if you manipulate both Binance and Coinbase completely, the median will still take the average of the sets (Uniswap V3, Balancer V2) and the manipulated set [Binance, Coinbase] which limits the effectiveness of the manipulated price as it's effectively buffered in half. Alternatively we have two sources priced in WETH so we are quite exposed to a WETH contract getting hacked.

**Data Model 2**
Uniswap V3 - HUGE market depth GNO/WETH
Balancer V2 - HUGE market depth  GNO/WETH
Binance GNO/USDT - $6,866 | $19,906 | $83,434
Coinbase GNO/USD - $14,925 | $13,882 | $25,080
Kraken GNO/USD - $1,321 | $7,797 | $8,473

With 5 sources so attacker needs to manipulate 3 of them. Because of Uniswap & Balancer's huge TVL, an attacker will most likely select Binance, Coinbase, and Kraken. So compared to Data Model 1, Data Model 2 may be better because you need to manipulate Kraken as well now. It is important to acknowledge that we are losing the 50% buffer that Uniswap V3 and Balancer were providing against the manipulated price set. Is this trade-off worth it? Because Kraken is fairly cheap to manipulate and we lose our buffer protection. Looking at alternative attacks, compared to Data Model 1 we don't have the dependency on WETH as an attack vector anymore. So that's good.

Ultimately I think Data Model 1 is better because it provides the buffer protection. Even though it has WETH exposure, I think the likelihood of WETH getting hacked is relatively low given how much money is in there and how long it has been around. 

So final GNO/USD Data Model is:
Uniswap V3
Balancer V2
Binance GNO/USDT 
Coinbase GNO/USD

2023-08-04 17:28 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "BNB/USD" {
[BNB/USD at notion](https://www.notion.so/BNB-USD-54cddc522c3441e483d6ed6531604d9e?pvs=4)

2023-08-04 17:29 UTC, deep-quality-dev commented on config-gofernext.hcl
>    data_model "USDC/USD" {
[USDC/USD at notion](https://www.notion.so/USDC-USD-bd16d5d638c848e4aca1abdc17a5cc2c?pvs=4)

2023-08-04 17:30 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "SOL/USD" {
[SOL/USD at notion](https://www.notion.so/SOL-USD-7eb52ae7c642490eaa9c4a1de45f9572?pvs=4)

2023-08-04 17:34 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "WBTC/USD" {
[WBTC/USD at notion](https://www.notion.so/WBTC-USD-c6f13a5a43a94157b2f1d292f570af90?pvs=4)

2023-08-04 17:35 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "AVAX/USD" {
[AVAX/USD at notion](https://www.notion.so/AVAX-USD-bafdcb6ef63348b198b40d582cb97414?pvs=4)

2023-08-04 17:35 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "DAI/USD" {
[DAI/USD at notion](https://www.notion.so/DAI-USD-af390dc218ca483287abb9bb051c8dfd?pvs=4)

2023-08-04 17:36 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "UNI/USD" {
[UNI/USD at notion](https://www.notion.so/UNI-USD-e613d06ff4bb453ca4ee867c5f0c44bf?pvs=4)

2023-08-04 17:36 UTC, deep-quality-dev commented on config-gofernext.hcl
>    data_model "LINK/USD" {
[LINK/USD at notion](https://www.notion.so/LINK-USD-3a992ee78ec24fc88cb67e7bbf9d927e?pvs=4)

2023-08-04 17:37 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "LDO/USD" {
[LDO/USD at notion](https://www.notion.so/LDO-USD-1cabdd69dd7045fbab251b5257a2e1ba?pvs=4)

2023-08-04 17:38 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "ARB/USD" {
[ARB/USD at notion](https://www.notion.so/ARB-USD-e9d653bc5458424a8f62830e35879fec?pvs=4)

2023-08-04 17:38 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "AAVE/USD" {
[AAVE/USD at notion](https://www.notion.so/AAVE-USD-e2a27aae983b454caf40d34c14c5b04c?pvs=4)

2023-08-04 17:39 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "FRAX/USD" {
[FRAX/USD at notion](https://www.notion.so/FRAX-USD-85ae39cf2c63459aaf5dad82cf42ed80?pvs=4)

2023-08-04 17:40 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "OP/USD" {
[OP/USD at notion](https://www.notion.so/OP-USD-49b4686d9ebc46af849edea2086b39d7?pvs=4)

2023-08-04 17:42 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "CRV/USD" {
[CRV/USD at notion](https://www.notion.so/CRV-USD-4f75983e37d44c768fe854a9c98551d8?pvs=4)

2023-08-04 17:42 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "SNX/USD" {
[SNX/USD at notion](https://www.notion.so/SNX-USD-208bc797d4974a4e96a8676b04d16c83?pvs=4)

2023-08-04 17:43 UTC, deep-quality-dev commented on config-gofernext.hcl
>    data_model "GNO/USD" {
[GNO/USD at notion](https://www.notion.so/GNO-USD-58b02c7c5b8d44b085a519a114658369?pvs=4)

2023-08-04 17:43 UTC, deep-quality-dev commented on config-gofernext.hcl
> +  data_model "XTZ/USD" {
[XTZ/USD at notion](https://www.notion.so/XTZ-USD-638178398644403a967a3e49222beaf8?pvs=4)

2023-08-14 11:35 UTC, MDobak submitted a review, later dismissed

2023-08-14 11:56 UTC, NiklasKunkel commented on config-gofernext.hcl
> -          origin "uniswapV3" { query = "WETH/USDC" }
I understand your desire to make ETH/USD 'pure' so it has no dependency on anything else. However the ETH/USD Oracle is such an important Oracle for us. It backs billions. Making sure there is no way for this Oracle to get manipulated is absolutely critical. I would suggest we keep UNIV3 ETH/USDC in the ETH/USD Data Model and remove it from the USDC/USD Data Model. For the USDC Data Model there are other alternative USDC based pools on Uniswap V3 we could substitute it with.

2023-08-14 11:56 UTC, NiklasKunkel requested changes
I've left my comments for modifications in the Notion documents for each Data Model.

2023-08-15 01:24 UTC, deep-quality-dev commented on config-gofer.hcl
> +      origin "bitstamp" { query = "AAVE/USD" }
Added `bitstamp` and set `min_values`=3 in `AAVE/USD`, reference [notion](https://www.notion.so/AAVE-USD-e2a27aae983b454caf40d34c14c5b04c?d=bfb4a0d968f44a25bfe857a4e4830dfc&pvs=4#adb29103a3df4e1d909dd36cfcd9cff0)

2023-08-15 01:25 UTC, deep-quality-dev commented on config-gofer.hcl
> +        origin "kucoin" { query = "OP/USDT" }
Added `kucoin` instead of `gate.io` in `OP/USD`, reference [notion](https://www.notion.so/OP-USD-49b4686d9ebc46af849edea2086b39d7?d=aa534f28ba7a44c794d4af4ec1063785&pvs=4#de46786beeba478a91545d75d1b1325c)

2023-08-15 01:25 UTC, deep-quality-dev commented on config-gofer.hcl
> +      min_values = 2
Set `min_values`=2 in `BNB/USD`, reference [notion](https://www.notion.so/BNB-USD-54cddc522c3441e483d6ed6531604d9e?d=ae009ebd106e47fbb429b9c57813bb20&pvs=4#a06c835497184e94880009a34f0c49a0)

2023-08-21 15:47 UTC, deep-quality-dev commented on config-gofernext.hcl
> -          origin "uniswapV3" { query = "WETH/USDC" }
Make sense to me, I rolled back Uniswap v3 ETH/USDC in ETH/USD data model and removed it from USDC/USD data model.
Unfortunately I can't find the alternative origin in USDC/USD, you can find the history [at notion](https://www.notion.so/USDC-USD-bd16d5d638c848e4aca1abdc17a5cc2c?d=704f409144ea4450ade4d3626af8bb38&pvs=4#2514cd944d8140b5977325884c987e80).

2023-08-24 20:51 UTC, NiklasKunkel approved these changes

2023-08-24 21:15 UTC, merged