Add Leeloo/Lair documentation [sc-438]
chronicleprotocol/oracle-suite pull request #22
Opened 2022-02-23 14:53 UTC by MDobak

2022-02-23 19:56 UTC, jar-o commented on cmd/lair/README.md
> +wish to work on Gofer source.
what's the relationship between Gofer and Lair? can that be clarified a bit here?

2022-02-23 19:58 UTC, jar-o commented
one small comment, but otherwise these docs look good to me.

2022-02-25 13:07 UTC, teghnet commented
How about updating to `config.json` with the new config values

2022-02-25 14:40 UTC, teghnet requested changes

2022-02-25 14:40 UTC, teghnet commented on cmd/leeloo/README.md
> +          "rpc": [
I think we need to change this key to something else than `rpc` as it is already used in other configs and looks like this:
```json
    "rpc": {
      "address": "127.0.0.1:9100"
    },
```
the meaning of `rpc` key is (because we have been using it like that) "the listtening address of an internal RPC server used to control the agent" .  Oh, and I know that `ethereum.rpc` is "external RPC server". 

Let's figure out some consistent semantics.

2022-02-25 14:40 UTC, teghnet commented on cmd/lair/README.md
> +    "address": "127.0.0.1:8082",
```suggestion
    "listenAddr": "127.0.0.1:8082",
```

2022-03-03 13:51 UTC, teghnet commented on cmd/lair/README.md
> +wish to work on Gofer source.
Gofer is the data source for prices that are then signed by Omnia/Ghost and Lair is a web API to get L2 Attestations

2022-03-05 11:42 UTC, MDobak commented on cmd/lair/README.md
> +    "address": "127.0.0.1:8082",
You're right, `listenAddr` would be more consistent. Fixed.

2022-03-05 11:44 UTC, MDobak commented on cmd/lair/README.md
> +wish to work on Gofer source.
Actually, it was a mistake. I removed reference to a Gofer.

2022-03-05 11:44 UTC, MDobak commented
I updated PR with documentation for RPC Splitter and also I added more details for Lair and Leeloo.

2022-03-05 13:03 UTC, merged