ComposableStablePool in Balancer V2[sc-2977]
chronicleprotocol/oracle-suite pull request #264
Opened 2023-09-28 13:52 UTC by deep-quality-dev

### description of pull request:

Balancer v2 supports `WeightedPool2Tokens`, `MetaStablePool`, `ComposableStablePool`, where the prior 2 types of pools supports Oracle functionality, the last one does not have.
In this PR,
- Implemented `ComposableStablePool` in `Balancer v2`, but as a separate origin due to the large code size and don't want to make any effect on the stable version
- Get the price by calculating the ratio between the expected amount output and given unit of amount input.

2023-10-06 14:00 UTC, MDobak requested changes
Overall, impressive work! I've compared your implementation to the JavaScript version, and they seem to match. I have just a few minor suggestions.

2023-10-30 16:40 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_pool.go
> +	} else {
It didn't need for now, just I am not sure when we will need it, but I've already added it in [unit test](https://github.com/chronicleprotocol/oracle-suite/pull/264/files#diff-74e0c9411f0e22e2036e21dfa0661abbdaacdc84a82e2002931c6b4a7bd9712dR131) as well.

2023-10-30 16:40 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_pool.go
> +}
Removed `Bytes32`, replaced with `types.Bytes`.

2023-10-30 16:43 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_pool.go
> +package origin
Agree with you, now `composable_stable*.go` do not export any function except construct function (New*), otherwise lowercased the function name or added underscore.

2023-10-30 16:45 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_math.go
> +package origin
Replaced `big.Int` with `bn.DecFloatPointNumber` and moved custom functions to `bn` package.
- MulDownFixed
- MulUpFixed
- DivUp
- DivUpFixed
- DivDownFixed
- Exp
- Inflate
- Deflate

2023-10-30 16:49 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_pool.go
> +}
I didn't move RPC calls into `ComposableStablePool`, because of reducing the times of [multicall](https://github.com/chronicleprotocol/oracle-suite/pull/264/files#diff-8a3a73f04967cce486eca494e3d0fc428e6baaa346db2f0a3371046e15706860R119) when we are asking multiple pairs.
Please let me know if I misunderstood you.

2023-12-04 05:23 UTC, MDobak commented on pkg/util/bn/decfloatpoint.go
> +// MulDownFixed multiplies the number y and deflates prec precision
Hm, I don't fully understand the purpose of the "Fixed" function. Why does reducing the precision make it fixed?

2023-12-04 05:24 UTC, MDobak commented on pkg/util/bn/decfloatpoint.go
> +}
Missing tests.

2023-12-04 05:28 UTC, MDobak commented on pkg/datapoint/origin/composable_balancer_v2.go
> +func (b *ComposableBalancerV2) FetchDataPoints(ctx context.Context, query []any) (map[any]datapoint.Point, error) {
Do yo think it'd be possible to split it into smaller functions?

2023-12-05 19:57 UTC, deep-quality-dev commented on pkg/util/bn/decfloatpoint.go
> +}
Removed Exp function

2023-12-05 20:04 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_balancer_v2.go
> +func (b *ComposableBalancerV2) FetchDataPoints(ctx context.Context, query []any) (map[any]datapoint.Point, error) {
Sure, I moved RPC calls into the ComposableBalancerPool.
Please check out the [commit](https://github.com/chronicleprotocol/oracle-suite/pull/264/commits/e463ce8412a0cc6882ce68c372ebf82709259252).

2023-12-05 20:15 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_pool.go
> +}
I moved RPC calls into the ComposableBalancerPool.
Please check out the [commit](https://github.com/chronicleprotocol/oracle-suite/pull/264/commits/e463ce8412a0cc6882ce68c372ebf82709259252).

2023-12-05 20:17 UTC, deep-quality-dev commented on pkg/util/bn/decfloatpoint.go
> +}
All the math functions newly added were used again in WeightedPool.
I've added their unit tests, you can check out [here](https://github.com/chronicleprotocol/oracle-suite/pull/302/files#diff-208848c5eff593a6fa634b12c13d6d3b2bf2fa7f09928fc5ee29ed4c36f75523R50).

2023-12-05 20:19 UTC, deep-quality-dev commented on pkg/util/bn/decfloatpoint.go
> +// MulDownFixed multiplies the number y and deflates prec precision
Fixed math functions were used to keep 18 decimals in every math operations in Balancer,
https://github.com/balancer/balancer-v2-monorepo/blob/master/pkg/solidity-utils/contracts/math/FixedPoint.sol
I've modified those functions to pass decimals.

2023-12-06 11:54 UTC, MDobak commented on pkg/util/bn/decfloatpoint.go
> +// MulDownFixed multiplies the number y and deflates prec precision
How this is different from `DecFixedPoint`?

2023-12-08 01:27 UTC, MDobak commented on pkg/util/bn/decfloatpoint.go
> +}
But the unit test should be written in the same package where the method is defined. Also, I checked the `DivUp` function and for `DecFloatPoint(106.25).DivUp(DecFloatPoint(4.25))` returns 25.76...? Please write unit tests for these functions, math functions are critical and I could not validate this PR with proper tests of this package.

2023-12-08 12:27 UTC, teghnet requested changes

2023-12-08 12:27 UTC, teghnet commented on pkg/util/bn/decfloatpoint.go
We need unit tests for this. 
Math is super important here.

2023-12-08 12:27 UTC, teghnet commented on suite.go
Good catch

2023-12-10 22:59 UTC, deep-quality-dev commented on pkg/util/bn/decfloatpoint.go
> +}
It makes sense to move **up/down functions to Balancer's math.
These are math functions for integers.
Reference:
https://www.cs.nott.ac.uk/~psarb2/G51MPC/slides/NumberLogic.pdf
https://github.com/libbitcoin/libbitcoin-system/wiki/Integer-Division-Unraveled

2023-12-10 23:20 UTC, deep-quality-dev commented on pkg/util/bn/decfloatpoint.go
I found that we don't need to add more functions for ComposableStablePool.
You can check out this [commit](https://github.com/chronicleprotocol/oracle-suite/pull/264/commits/c10e8a8642133635d03df9feda725fb9c6fa0471).

2023-12-10 23:21 UTC, deep-quality-dev commented on pkg/datapoint/origin/composable_stable_pool.go
> +	} else {
I removed BPT token swapping since we won't use that as you mentioned.

2023-12-19 14:24 UTC, MDobak approved these changes

2023-12-19 15:18 UTC, merged