Export hcl with command line[sc-3088]
chronicleprotocol/oracle-suite pull request #279
Opened 2023-10-20 19:49 UTC by deep-quality-dev

### description of pull request:

- Run the following command to export in-memory config to hcl format on console:
   `ghost run --config.hcl`

2023-10-25 10:10 UTC, deep-quality-dev commented on pkg/util/hcl/decode.go
> +	pairTy        = reflect.TypeOf((*value.Pair)(nil)).Elem()
The above two lines requires to import the following packages under `pkg/util/hcl/decode.go`:
```
github.com/defiweb/go-eth/types
github.com/chronicleprotocol/oracle-suite/pkg/datapoint/value
```
Do you have any idea of not importing those packages? @MDobak 

My original idea was mapping from `types.Address`, `value.Pair` to `cty.StringValue`.

2023-10-30 15:27 UTC, teghnet commented
How do we handle secrets?

2023-10-30 17:10 UTC, deep-quality-dev commented
> How do we handle secrets?
> 
> Also, I think that it would be good to have a test ([Example](https://go.dev/blog/examples)) for the config not changing by accident. For example: comparing to a static file like: https://github.com/chronicleprotocol/oracle-suite/blob/master/cmd/gofer/testdata/models.txt

I will add another test to see how the exported file looks like.
Exported data will include the private key, I need to skip comparing the `key` under `ethereum` tag.
```
ethereum {
  key "default" {
    address       = "0x5c01f0f08e54b85f4cab8c6a03c9425196fe66dd"
    keystore_path = "..."
  }
  ...
}
```

2023-11-01 19:48 UTC, teghnet commented
Would also be nice to have same test cases for when
`                  CFG_ENVIRONMENT=stage`

That is the main difference between envs.
1. in prod `CFG_ENVIRONMENT` is not set
2. in staging `CFG_ENVIRONMENT=stage`

2023-11-03 11:48 UTC, teghnet reviewed
Why create `common` package?
Why move from `cmd`?

2023-11-03 12:28 UTC, deep-quality-dev commented
> Why create `common` package? Why move from `cmd`?

After adding `--config.hcl`, it requires to add the test cases and test data, and particularly test data contains number of blob files. I think would be better to put them all into `common` package, while these files in `common` are already used in other `cmd` files.
If you have any better idea, please let me know.

2023-11-07 15:13 UTC, teghnet requested changes
> > Why create `common` package? Why move from `cmd`?
> 
>  If you have any better idea, please let me know.

Please do not add the `common` package here
- keep the stuff in `cmd`
- or move it to `pkg/utils/cmd` or something like that

2023-11-07 20:31 UTC, deep-quality-dev commented
> Please do not add the `common` package here
> 
> * keep the stuff in `cmd`
> * or move it to `pkg/utils/cmd` or something like that

Moved `common` package to `cmd`, and left test go and test data under `test` folder

2023-11-08 13:16 UTC, MDobak commented on pkg/util/hcl/decode.go
> +	pairTy        = reflect.TypeOf((*value.Pair)(nil)).Elem()
They could be handled using `TextMarshaler` and `TextUnmarshaler` interfaces instead.

2023-11-08 13:18 UTC, MDobak commented on pkg/util/hcl/decode.go
> +}
`fmt.Stringer` could be used instead

2023-11-08 13:23 UTC, MDobak commented on pkg/util/hcl/decode.go
> +}
I think this logic is too specific, could this be replaced with `TextMarshaler`, `TextUnmarshaler`, and `Marshaler` and `Unmarshaler` interfaces instead?

2023-11-08 13:25 UTC, MDobak commented on pkg/util/hcl/decode.go
> +}
After this change, those functions are not related only to decoding, so perhaps it would make sense to move them to a separate file?

2023-11-08 20:15 UTC, deep-quality-dev commented on pkg/util/hcl/decode.go
> +	pairTy        = reflect.TypeOf((*value.Pair)(nil)).Elem()
`pairTy` and `strMapper` were created to marshal value.Pair `hcl:"pair,label"` to string.
I removed `strMapper` and manually [marshaled for labels](https://github.com/chronicleprotocol/oracle-suite/pull/279/files#diff-223e2dace14cbc8b5111167667856ed1f0b09883cd37e5c43dbd8fbd5b529b10R48) in `EncodeAsBlock` function.

2023-11-08 20:16 UTC, deep-quality-dev commented on pkg/util/hcl/decode.go
> +}
Deprecated `strMapper` and `stringize`, and used `fmt.Stringer` instead.

2023-11-08 20:22 UTC, deep-quality-dev commented on pkg/util/hcl/decode.go
> +}
I deprecated the `strMapper`.
Reason:
`strMapper` was designed to map `value.Pair` for label to string.
In the `Mapper.mapperFor()`, the mapper function of src(`value.Pair`) and dst(`string`) was not found, because `isSrcSimple` is false for `value.Pair` and `isDstSimple` is true(`string`) but not same types.
So without adding `typeof(value.Pair)` to the mapper, mapper function always returns nil function.

2023-11-08 20:22 UTC, deep-quality-dev commented on pkg/util/hcl/decode.go
> +}
I also think so, moved them to `mapper.go`

2023-11-09 11:59 UTC, teghnet submitted a review, later dismissed

2023-11-09 13:50 UTC, MDobak commented
Hey, I'd like to go once again through the code today so please wait with merge a little bit more :)

2023-11-09 16:47 UTC, teghnet commented on cmd/command.go
> +			if argued, err := f.Load(c); err != nil || argued {
What is the intention behind this condition?

2023-11-09 16:52 UTC, deep-quality-dev commented on cmd/command.go
> +			if argued, err := f.Load(c); err != nil || argued {
> What is the intention behind this condition?

In the `main` branch, when giving arguments in command, like `--config.json or --config.hcl`, exits app at the end/
I changed `ConfigFlag::Load()` function to return seamlessly without exiting itself.
This change helps us to continue number of unit tests.

2023-11-09 16:54 UTC, deep-quality-dev commented on cmd/command.go
> +			if argued, err := f.Load(c); err != nil || argued {
If run app with command arguments, do not continue running services.

2023-11-14 01:24 UTC, teghnet commented on cmd/command.go
> +		Use:   "render-config",
How about we use `config` as the command name, just like e.g. `docker compose`
```suggestion
		Use:   "config",
```

2023-11-14 01:24 UTC, teghnet submitted a review, later dismissed

2023-11-14 10:21 UTC, merged