On-Chain Config App initializer[sc-3242]
chronicleprotocol/oracle-suite pull request #294
Opened 2023-11-17 12:51 UTC by deep-quality-dev

### description of pull request:

Create `morph` app that works as oracle-suite initializer, which is responsible for 
- keeping up-to-dated config from `ConfigRegistry`
- running app with up-to-dated config.
- if on-chain config has been updated, restart app via sending interrupt signal.

#### Run `morph` with embedded config(`config-morph.hcl`)
```bash
./morph run
```

#### Run `morph` with arguments
```bash
./morph run --bin ./ghost --config config-cache.hcl --config-rpc [rpc url] --config-registry [ConfigRegistry address]
```
With this command, morph will prioritize the arguments to run.
`--bin`: required, indicates a command to run application
`--config`: optional, indicates a path to the local config file being loaded when app starts running
`--config-rpc`: optional, indicates a rpc url to be used to fetch on-chain config from ConfigRegistry contract
`--config-registry`: optional, indicates a address to ConfigRegistry contract

2023-11-23 14:00 UTC, teghnet requested changes
Generally, we need more documentation on how this code is to behave.
Not all is obvious.

2023-11-23 14:00 UTC, teghnet commented on pkg/morph/morph.go
> +func (m *Morph) RestartApp() error {
I think we discussed, that we want the app to exit and let k8s (or whatever orchestration we have) restart it.

2023-11-23 17:27 UTC, teghnet commented on pkg/supervisor/appmanager.go
> +	am.ctx = ctx
Let's check if app is already running.
ie. check if ctx is not null

2023-11-23 23:19 UTC, deep-quality-dev commented on pkg/supervisor/appmanager.go
> +	am.ctx = ctx
I need to check if app is already running. As `morph` initiate the `ghost` at the beginning, if `morph` was killed or crashed for some reason, `morph` might rerun app at the next running. 
So in order to keep only one process is running, I need to kill the existing process before start running `ghost`.

2023-11-23 23:19 UTC, deep-quality-dev commented on pkg/morph/morph.go
Replaced `morph` in pkg with `watchdog`

2023-11-23 23:20 UTC, deep-quality-dev commented on cmd/morph/cmd_run.go
> +			}
Removed setting env vars and we can use same `run` command with other apps.

2023-11-24 16:18 UTC, teghnet commented on pkg/supervisor/appmanager.go
> +	am.ctx = ctx
I mean 
```go
	if s.ctx != nil {
		return errors.New("service can be started only once")
	}
	if ctx == nil {
		return errors.New("context must not be nil")
	}
```

2023-11-27 19:40 UTC, closed without merging