Add DeGate origin
chronicleprotocol/oracle-suite pull request #301
Opened 2023-11-28 05:04 UTC by deep-quality-dev

### description of pull request:

- Add DeGate origin

### reference
https://github.com/degatedev/degate-sdk-golang
https://api-docs.degate.com/spot/#24hr-ticker-price-change-statistics

2023-12-04 05:56 UTC, MDobak requested changes

2023-12-04 05:56 UTC, MDobak commented on pkg/datapoint/origin/degate.go
> +	// QuoteVolume     string `json:"quote_volume"`
If this is not used, just remove it.

2023-12-04 05:56 UTC, MDobak commented on pkg/datapoint/origin/degate.go
> +		}
What's the purpose of this check? Why there's a need to provide a list of supported pairs in the config struct?

2023-12-06 07:44 UTC, MDobak commented on pkg/datapoint/origin/degate.go
> +		}
> I think specifying the supported pairs helps us to understand which pairs use DeGate, vise versa. Wdyt?

We're not doing it for any other origin, and we always conduct research before making a pricing model, so I don't think these kinds of checks would ever be useful.

2023-12-06 09:33 UTC, deep-quality-dev commented on pkg/datapoint/origin/degate.go
> +		}
Good catch, removed pairs in this [commit](https://github.com/chronicleprotocol/oracle-suite/pull/301/commits/50aa526d83c1d96f6231c012c80df795116b56d9).

2023-12-06 12:37 UTC, closed without merging