Added configurable endpoints
chronicleprotocol/oracle-suite pull request #6
Opened 2021-12-02 17:34 UTC by konstantinzolotarev

2021-12-06 15:59 UTC, teghnet requested changes
The base uri should be consistent with the origin. 
I's goiin to be cleanner to use theGraphURL where it is needed, because the implementation is already origin specific.

re: https://github.com/makerdao/setzer-mcd/pull/39

2021-12-06 15:59 UTC, teghnet commented on pkg/gofer/origins/balancer.go
> +const balancerBaseURL = "https://api.thegraph.com"
very much related to https://github.com/makerdao/setzer-mcd/pull/39

2021-12-07 15:13 UTC, teghnet approved these changes

2021-12-13 13:52 UTC, MDobak reviewed
Can we add tests for that feature in `gofer_test.go`?

2022-01-10 10:31 UTC, merged